# Generated by Django 5.0.1 on 2024-01-10 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_time', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lunch_time.question'),
            preserve_default=False,
        ),
    ]
