# Generated by Django 5.0.1 on 2024-01-10 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_time', '0002_name_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch_time.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch_time.question')),
            ],
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
