# Generated by Django 5.0.1 on 2024-01-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_waiting',
            field=models.BooleanField(default=False),
        ),
    ]
