# Generated by Django 5.0.1 on 2024-01-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0002_player_is_waiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='num_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='num_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='time_played',
            field=models.IntegerField(default=0),
        ),
    ]
